version: '3.9'

services:
  api:
    build: 
      context: ./Aldatech.API
      dockerfile: ./Dockerfile
    command: dotnet run
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ssl_pass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - postgres
    networks:
      - aldatech-network
    volumes:
      - ~/.aspnet/https:/https:ro #this is very important

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=aldatech_db
      - POSTGRES_USER=aldatech_user
      - POSTGRES_PASSWORD=aldatech_password
    expose:
      - 5432
    # volumes:
    #   - db_volume:/var/lib/postgresql/data
    shm_size: 1g
    networks:
      - aldatech-network

networks:
  aldatech-network:
    driver: bridge 

volumes:
  db_volume:

  